# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tanmay Fadnavis
tagline:          'My Website'
url:              https://tanmayfadnavis.github.io/

author:
  name:           'Tanmay Fadnavis'
  url:            https://twitter.com/tanmayfadnavis

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/TanmayFadnavis
