# Dependencies
#markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Tanmay Fadnavis
tagline:          'My Website'
url:              https://tanmayfadnavis.github.io/

author:
  name:           'Tanmay Fadnavis'
  url:            https://twitter.com/tanmayfadnavis

paginate:         5

# Custom vars
version:          2.1.0

plugins: 
  - jekyll-paginate
  - jekyll-gist

github:
  repo:           https://github.com/TanmayFadnavis
